[package]
name = "aa-core"
version = "1.0.0"
edition.workspace = true
license.workspace = true

[features]
default = ["parallel", "benchmark"]
parallel = ["dep:rayon"]
benchmark = ["parallel"]

[dependencies]
fontdue.workspace = true
image.workspace = true
imageproc.workspace = true
rayon = { workspace = true, optional = true }
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
ttf-parser.workspace = true
web-time.workspace = true
